#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TARGET_ROOT="${CODEX_HOME:-$HOME/.codex}/skills"
LOCAL_CODEX_DIR="$REPO_ROOT/.codex"

mkdir -p "$TARGET_ROOT"
mkdir -p "$LOCAL_CODEX_DIR"

link_skill() {
  local skill_name="$1"
  local source_path="$SCRIPT_DIR/$skill_name"
  local target_path="$TARGET_ROOT/$skill_name"

  if [[ ! -d "$source_path" ]]; then
    echo "Skipping missing skill: $skill_name"
    return
  fi

  rm -rf "$target_path"
  ln -s "$source_path" "$target_path"
  echo "Linked $skill_name -> $target_path"
}

link_skill "tool-commit-push"
link_skill "tool-create-pr"
link_skill "local-code-conventions"
link_skill "local-styled-components"

cat > "$LOCAL_CODEX_DIR/README.md" <<'EOF'
# Codex Project Integration

This directory is generated by:

```bash
npm run skills:setup
```

Project source of truth:

- `AGENTS.md`
- `skills/`

Installed skills are linked into the global Codex directory:

- `~/.codex/skills`
- or `$CODEX_HOME/skills` when `CODEX_HOME` is set
EOF

cat > "$LOCAL_CODEX_DIR/project.json" <<EOF
{
  "name": "wedding-luis-montse",
  "skillsSource": "./skills",
  "agentsGuide": "./AGENTS.md",
  "installCommand": "npm run skills:setup"
}
EOF

echo "Generated $LOCAL_CODEX_DIR"
echo "Skills installed into $TARGET_ROOT"
