export const adminCopy = {
  attending: 'Asistentes',
  attendance: 'Asistencia',
  attendanceAttending: 'Asistirá',
  attendanceDeclined: 'No asistirá',
  attendancePending: 'Sin responder',
  allergies: 'Alergias',
  addGuest: 'Añadir comensal',
  close: 'Cerrar',
  contactPhone: 'Teléfono de contacto',
  copyLink: 'Copiar enlace de WhatsApp',
  linkCopied: 'Enlace copiado',
  deleteConfirmation: 'Se eliminará esta invitación y todos sus comensales. ¿Quieres continuar?',
  deleteTitle: 'Eliminar invitación',
  cancel: 'Cancelar',
  confirmDelete: 'Eliminar invitación',
  deleteInvitation: 'Eliminar invitación',
  created: 'Invitación creada.',
  createInvitation: 'Nueva invitación',
  declined: 'No asistirán',
  dietary: 'Opciones alimentarias',
  editInvitation: 'Editar invitación',
  editWarning: 'Al eliminar un comensal se eliminará también su respuesta.',
  exportCsv: 'Exportar CSV',
  detailError: 'No hemos podido cargar el detalle de esta invitación.',
  email: 'Email de administración',
  empty: 'Todavía no hay invitaciones creadas.',
  group: 'Grupo',
  hideGuests: 'Ocultar comensales',
  guests: 'Comensales',
  guestName: 'Nombre del comensal',
  guestNames: 'Comensales incluidos',
  actions: 'Acciones',
  groupName: 'Nombre del grupo',
  loginDescription: 'Acceso privado para gestionar las confirmaciones.',
  loginError: 'No hemos podido enviar el enlace. Comprueba el email autorizado.',
  loginSent: 'Te hemos enviado un enlace de acceso.',
  loginSubmit: 'Enviar enlace de acceso',
  loginTitle: 'Gestión de invitados',
  invitationLanguage: 'Idioma de la invitación',
  invitationImage: 'Imagen de la invitación',
  tableImage: 'Imagen',
  invitationImageAction: 'Seleccionar imagen',
  invitationImageHint: 'JPG, PNG o WebP. Máximo 5 MB.',
  removeInvitationImage: 'Quitar imagen',
  invitationSent: 'Enviada',
  languageCa: 'Catalán',
  languageEs: 'Castellano',
  noDetails: 'Sin observaciones',
  noPhone: 'Sin teléfono de contacto',
  observations: 'Observaciones',
  logout: 'Cerrar sesión',
  pending: 'Pendientes',
  responseDetails: 'Detalle de respuesta',
  searchInvitations: 'Buscar grupo',
  noSearchResults: 'No hay invitaciones que coincidan con esta búsqueda.',
  saveInvitation: 'Crear invitación',
  saveChanges: 'Guardar cambios',
  submitted: 'Respondido',
  showGuests: 'Ver comensales',
  title: 'Gestión de invitados',
  total: 'Total invitados',
  viewDetails: 'Ver detalle',
  unauthorized: 'Este usuario no tiene permisos de administración.',
  updated: 'Actualizado',
};
