export const rsvpFormCopy = {
  allergy: 'Alergias o intolerancias',
  allergyPlaceholder: 'Indica cualquier información relevante',
  attendance: '¿Asistirá?',
  details: 'Completa una respuesta por cada persona incluida en vuestra invitación.',
  dietary: 'Opciones alimentarias',
  dietaryOptions: ['Vegano', 'Vegetariano', 'Celíaco', 'Sin lactosa'],
  extraDetails: 'Menú, alergias y observaciones',
  error: 'No hemos podido cargar esta invitación. Comprueba que has abierto el enlace completo.',
  invalidLink: 'Este enlace de confirmación no es válido.',
  loading: 'Cargando invitación...',
  no: 'No podré asistir',
  notes: 'Observaciones',
  notesPlaceholder: 'Cualquier otro detalle importante para nosotros',
  saved: 'Gracias. Hemos guardado vuestra respuesta.',
  savedEdit: 'Editar respuesta',
  savedReturn: 'Ir a la boda',
  saving: 'Guardando...',
  send: 'Enviar confirmación',
  title: 'Confirmación de asistencia',
  yes: 'Sí, asistiré',
};
